### ISSUE TITLE
ADD & in htmlUnescape 

### ISSUE THREAD

**Issue by Akshat1993** [enonic/lib-text-encoding#6]
I am getting error while parsing string contains `&` character

**Comment by aro** [comment]
Can you explain the context of what you are trying to do?

Please include an example of the code that fails so we can reproduce it, and fix in case it is a bug.

**Comment by alansemenov** [comment]
@Akshat1993 do you have any example that we can follow up?

**Comment by alansemenov** [comment]
@Akshat1993 reopen this if you can provide an example we could use
